# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

language: java
jdk:
  - openjdk8

script:
  - ./mvnw clean package -Djarsigner.skip=false

after_success:
- ./mvnw test jacoco:report coveralls:report

cache:
  directories:
  - $HOME/.m2

notifications:
  slack:
    secure: "NEuhkmcxHCJoTpCqhWLoDXN0UkMbEwFvzxnU/8HqT/g06R3+0vdSbH8/oZ0srp3JsbMFeQuXA3tynT0EPRrCtlbYXdWBJTOGUDGJOC//VZm0zZa0+10KJOsHCKMpmoYjCS81N13UW6EGdu5U3jY4It/5mIOPNz6v9c9XLzt8hkgkbRihV+lfRTPiK6N+TmBzgZWQCDBhqHHhZzejuCMvniFlJCTQLh4QLECbjqUIerO14Pv7xXKFb1ZKLpi/BIjpB/HF6bAUPOAxjQX8R6T4o0vEfNCNyHIlSDPbxf5c7Mk83BG2nERVZKZLqyhVYkdfC4Ik7CWiTzp4OI79vFQ59lHZstvrICsOmM+p9X/S/x0FcuZTsY6jRwTtJlFTPyCcwQb/g0rnIX3gTZL6Ge5Plng4P+2yI4xweMGHa/jHlkgVL4EtInnABgLtaPXc6cis2o1wZtY0NedoG5vRRf0U8Q4NcEWpTZSzhrTBoEAC0Scvie6NKC5TckiLSTpWhqSGOz/qR55JcBsL41PqezEeNwnMyZ/1ZFKmNI4yo3jS/xXz7PLmXbxyPGfEi20PZyWQhrmwgXKIwMkDaZm63SJ0J2EpufYFrntRJJu2zOxW4kMkXGxoQFVF6sxE90e+HkZxdoGNgPJ4TYF/575qjpVLJ70goA1r8y3PkqJCboSUkMU="
  email: false
